version: '3.8'

services:
  db_rin:
    image: mysql:latest
    container_name: racer_rin_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: rin_db
      MYSQL_USER: rin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_rin_data:/var/lib/mysql

  db_buro:
    image: mysql:latest
    container_name: racer_buro_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: buro_db
      MYSQL_USER: buro
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_buro_data:/var/lib/mysql

  db_marija:
    image: mysql:latest
    container_name: racer_marija_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: marija_db
      MYSQL_USER: marija
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - db_marija_data:/var/lib/mysql

volumes:
  db_rin_data:
  db_buro_data:
  db_marija_data: